export const constants = {
  companyName:"Meal Planner",
  copyright:" Copyright 2021 All Rights Reserved by",
  contactNo:"0123456789",
  contactEmail:"support@email.com",
  minerals : ["calcium", "phosphorus", "potassium", "sodium", "chloride", "magnesium", "iron", "zinc", "iodine", "chromium", "copper", "fluoride", "sulfur", "molybdenum", "manganese","selenium", "fat", "protein", "carbs" ],
  dietLabels: ["Balanced", "High-Fiber","High-Protein", "Low-Carb", "Low-Fat", "Low-Sodium"],
  healthLabels: ["Vegetarian", "Vegan","Peanut-free", "Low potassium", "Alcohol-free"],
  nutrientDbFields:["fat","carbs","protein","cholesterol","sodium","calcium","magnesium","potassium","iron","zinc","phosphorus","vitamin_a","vitamin_c","thiamin_b1","riboflavin_b2","niacin_b3","vitamin_b6","folate_equivalent_total","folate_food","folic_acid","vitamin_b12","vitamin_d","vitamin_e","vitamin_k","sugar_alcohols",
        "water","energy","saturated","monounsaturated","polyunsaturated","fiber","sugars","sugars_added"],
  edamam_nutrient_api :"https://api.edamam.com/api/nutrition-data",
  healthLabelsNew: ["Vegetarian","Pescatarian","Egg-Free","Peanut-Free", "Tree-Nut-Free","Soy-Free","Fish-Free","Shellfish-Free","Pork-Free","Red-Meat-Free","Crustacean-Free","Celery-Free","Mustard-Free", "Sesame-Free","Lupine-Free","Mollusk-Free","Alcohol-Free", "Kosher","Kidney-Friendly","Gluten-Free", "Wheat-Free","Vegan","Dairy-Free","Sugar-Conscious", "Immuno-Supportive","No oil added","Low Potassium", "Keto-Friendly","FODMAP-Free"],

  healthLabelsWithImages: [
    {"name":"Vegetarian", "image":"assets/images/vegetarian.png"},
    {"name":"Pescatarian", "image":"assets/images/pescatarian.png"},
    {"name":"Egg-Free", "image":"assets/images/free-egg.png"},
    {"name":"Peanut-Free", "image":"assets/images/peanut-free.png"},
    {"name":"Vegan","image":"assets/images/vegan.png"},
    {"name":"Tree-Nut-Free", "image":"assets/images/free-nut.png"},
    {"name":"Dairy-Free","image":"assets/images/free-dairy.png"},
    {"name":"Keto-Friendly","image":"assets/images/keto-diet.png"},
    {"name":"Gluten-Free", "image":"assets/images/free-gluten.png"},   
    {"name":"Alcohol-Free", "image":"assets/menu/alcoholfree.png"},     
    {"name":"Soy-Free","image":"assets/images/tick.png"},
    {"name":"Fish-Free","image":"assets/images/tick.png"},
    {"name":"Shellfish-Free","image":"assets/images/tick.png"},
    {"name":"Pork-Free","image":"assets/images/tick.png"},
    {"name":"Red-Meat-Free","image":"assets/images/tick.png"},
    {"name":"Crustacean-Free","image":"assets/images/tick.png"},
    {"name":"Celery-Free","image":"assets/images/tick.png"},
    {"name":"Mustard-Free", "image":"assets/images/tick.png"},
    {"name":"Sesame-Free","image":"assets/images/tick.png"},
    {"name":"Lupine-Free","image":"assets/images/tick.png"},
    {"name":"Mollusk-Free","image":"assets/images/tick.png"},
    {"name":"Kosher","image":"assets/images/tick.png"},
    {"name":"Kidney-Friendly","image":"assets/images/tick.png"},
    {"name":"Wheat-Free","image":"assets/images/tick.png"},   
    {"name":"Sugar-Conscious", "image":"assets/images/tick.png"},
    {"name":"Immuno-Supportive","image":"assets/images/tick.png"},
    {"name":"No oil added","image":"assets/images/tick.png"},
    {"name":"Low Potassium", "image":"assets/images/tick.png"}, 
    {"name":"FODMAP-Free","image":"assets/images/tick.png"}
  ],
  "colors":["#FF3155", "#FFAF42", "#FFED5E", "#49F770", "#2DAEFD", "#FF3155","#003f5c","#58508d","#f2f1f1", "#FFFFFF"],
  "colorslist":[
      ["#0D1F73", "#17469F", "#2969BA", "#3A89C0", "#4AA7B3", "#59C39B","#6ADC7F"],
      ["#FF3155", "#FFAF42", "#FFED5E", "#49F770", "#2DAEFD", "#FF3155","#003f5c"],
      ["#5899DA", "#E8743B", "#19A979", "#ED4A7B","#945ECF","#13A4B4","#525DF4"],
      ["#B26E39", "#FE9D52", "#FFCEA9", "#DDDDDD","#9ECBED","#3C97DA","#2A6A99"],
      ["#142458", "#186BA1", "#19ABDE", "#1AC9E6","#1BD5D4","#1DE4BD","#6DF0D1"],
      ["#27076A", "#7C3AC0", "#AF4BCF", "#DA4CB2","#EC548D","#E97369","#F0A58E"],
      ["#810400", "#C02322", "#DE542D", "#EF7E32","#EE9A3A","#EABE3B","#E7E34E"],
      ["#1F77B4", "#FF7F0E", "#2CA02C", "#D62728","#9467BD","#8C564B","#E377C2"],
      ["#2CA02C", "#BCBD22", "#1F77B4", "#D62728","#9467BD","#F9CB9C","#FF9900"]
      ],
  "cusineType":["american","british","caribbean","central europe","chinese","eastern europe","italian","korean","bulgogi","mediterranean","nordic","south american","south east asian","asian","central europe","indian","japanese","middle eastern","south east asian","french","greek","italian","mexican","kosher"],
  "cusineTypeList":["american","asian","chinese","french","italian","indian","japanese","kosher","mexican","korean"]
};


