export const environment = {
  production: true,
//  apiUrl:"https://www.dentavacation.com/mobileapp/api",
apiUrl:"https://mealplannerapi-otkcj.ondigitalocean.app/api",
  appUrl:"https://www.fitaholic.com",
  //playstoreUrl: "https://play.google.com/store/apps/details?id=com.mtc.mob",
  playstoreUrl: "",
  appname:"fitaholic",
  accessToken:"",
  fromname: "Team MTC",
  fromemail:"<contact@medicaltourismco.com>",
  companyname: "MTC",
   contactToName:"Admin",
  contactEmail: "contact@medicaltourismco.com",
  edamameId: "eaec56cb",
  edamameKey: "a9fec70780e435632a893d2d10eee322",
  google_clientId:"269097500191-nieo8fcaf4vlbrl30mg9c6p60c2spl5i.apps.googleusercontent.com",
  facebook_appid: "325439192274708",
  scrapeurl:"https://my-newapi.herokuapp.com/"
};
